export const FETCH_BOARDS_BEGIN = "FETCH_BOARDS_BEGIN"
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS"
export const FETCH_BOARDS_ERROR = "FETCH_BOARDS_ERROR"

export const FETCH_BOARD_DETAILS_BEGIN = "FETCH_BOARD_DETAILS_BEGIN"
export const FETCH_BOARD_DETAILS_SUCCESS = "FETCH_BOARD_DETAILS_SUCCESS"
export const FETCH_BOARD_DETAILS_ERROR = "FETCH_BOARD_DETAILS_ERROR"
export const RESET_FETCH_BOARD_DETAILS = "RESET_FETCH_BOARD_DETAILS"

export const CREATE_BOARD_BEGIN = "CREATE_BOARD_BEGIN"
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS"
export const CREATE_BOARD_ERROR = "CREATE_BOARD_ERROR"
export const RESET_CREATE_BOARD = "RESET_CREATE_BOARD"

export const EDIT_BOARD_BEGIN = "EDIT_BOARD_BEGIN"
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS"
export const EDIT_BOARD_ERROR = "EDIT_BOARD_ERROR"

export const DELETE_BOARD_BEGIN = "DELETE_BOARD_BEGIN"
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS"
export const DELETE_BOARD_ERROR = "DELETE_BOARD_ERROR"
export const RESET_DELETE_BOARD = "RESET_DELETE_BOARD"

export const CLEAR_BOARD_BEGIN = "CLEAR_BOARD_BEGIN"
export const CLEAR_BOARD_SUCCESS = "CLEAR_BOARD_SUCCESS"
export const CLEAR_BOARD_ERROR = "CLEAR_BOARD_ERROR"
export const RESET_CLEAR_BOARD = "RESET_CLEAR_BOARD"

export const SET_CURRENT_BOARD = "SET_CURRENT_BOARD"